### PR TITLE
Django 1.7 Support

### PR DESCRIPTION
**Pull request by bitmonkey**
It's Django upgrade time at ISM so expect a pull request when I've figured out what if anything needs doing to support Django 1.7

### CODE REVIEW

**Comment by bitmonkey** [comment]
Know I can technically merge this myself, but would rather other potentially concerned parties run their brains over my changes first @danfairs @robcharlwood @mhsparks

**Comment by robcharlwood** [comment]
@bitmonkey looks fine to me mate! :)

**Comment by bitmonkey** [comment]
Merging in as noone's piped up :)

**Comment by robcharlwood** [comment]
@bitmonkey Yeah, may as well mate. What you have done looks totally fine to me. I checked it all out and tox tests all ran fine etc and my local test project didnt break. Don't forget to release a version to PyPy. :)

**Comment by bitmonkey** [comment]
Just sorting out a sdist release for pypi now :)

**Pull request merged**
